### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by PoiScript** [PoiScript/Solomon#1]
- [x] Pre-Bootstrap splash screen

- [x] Redesign the PostListComponent

- [x] github-markdown-css

**Comment by PoiScript** [comment]
Added [github-markdown-css](https://github.com/sindresorhus/github-markdown-css).

**Comment by PoiScript** [comment]
Added PostPreviewComponent instead of redesigning PostListComponent.

**Comment by PoiScript** [comment]
According to the issues in angular-cli, `ng server -aot` & `ng build -aot` can't work with lazy load modules for now(beta 30), so I removed **Add i18n support** from to-do now.

**Comment by PoiScript** [comment]
Added splash screen
